### ISSUE TITLE
The game doesn't bootup when offline

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#185] opened 2024-04-06 18:26 UTC
So basically, when you're offline like if you don't have any internet, and when trying to play the mod, the game just closes when starting up.

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/6ec56398-f585-4f2b-87b9-8842784546c5

[2024-04-07-1.log](https://github.com/Wilyicaro/Legacy-Minecraft/files/14897625/2024-04-07-1.log)

**Comment by omo50** [comment] 2024-04-06 18:28
offline mode allows for cracked minecraft. i doubt this is going to be supported

**Comment by DanielMC101** [comment] 2024-04-06 18:31
@omo50 this could be a problem if you don't have access to internet and you really wanna play the mod

**Comment by omo50** [comment] 2024-04-07 02:27
> @omo50 this could be a problem if you don't have access to internet and you really wanna play the mod

that is a very arbitrary case. offline mode is cracked, in this case just wait for wifi to turn back on
in the l4j server you also had others saying it worked fine. can you reproduce consistently?

**Comment by DanielMC101** [comment] 2024-04-07 14:15
@omo50 dude, I'm basically saying that in scenarios where you can't have access to wifi like if u wanna play this mod on a portable device like airplane, or in a car, etc.

**Comment by omo50** [comment] 2024-04-07 14:17
kek

Only way I (or others) can help you is if you provide log and crash report to give more info

**Comment by DanielMC101** [comment] 2024-04-07 14:40
@omo50 i added the log, there's no crash report it seems like

**Comment by omo50** [comment] 2024-04-07 14:45
Update your fabric loader to 0.15.9 and try again

**Comment by DanielMC101** [comment] 2024-04-07 17:45
@omo50 nope, still doesn't work

**Comment by omo50** [comment] 2024-04-07 17:54
the issue comes from you not being able to connect to mojang servers. I dont know what you want to be fixed considering offline mode is cracked minecraft. In such a niche circumstance where you're on an airplane, playing on a handheld, i think you can wait to play this mod

**Comment by omo50** [comment] 2024-04-07 17:55
er, offline mode can be *used* for cracked mc
still, unfixable

**Comment by DanielMC101** [comment] 2024-04-07 18:07
@omo50 the thing is, other mods, it seems to work just fine.

**Comment by omo50** [comment] 2024-04-07 18:08
you can stop @'ing me
But i doubt this will be worked out due to how it can be used to support cracked/pirated minecraft

**Comment by Wilyicaro** [comment] 2024-04-28 00:59
Fixed in version 1.6, thanks for reporting.

**Closed by Wilyicaro** 2024-04-28 00:59 UTC
