### ISSUE TITLE
trident enchantment books dont have enchantments

### ISSUE THREAD

**Issue by Cookie-Developer** [Wilyicaro/Legacy-Minecraft#436] opened 2024-06-01 22:17 UTC
in the trident tutorial area, none of the books have enchantments on them
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/91225097/d5a06ed0-60be-48c7-afb8-8940643dc9ff)
(i already used the exp bottles in the picture)
all of the books are like this.

running 1.20.6 on fabric

**Comment by bugsbugsbugsLCE** [comment] 2024-06-05 18:33
There are probably more issues like these caused by world conversion.
![2024-06-05_20 31 19](https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/630acf95-ac78-46e5-b925-f9d2ebbfdc2b)
Surprisingly the enchanted book in the anvil are enchanted with fire aspect as expected.

**Comment by tristann21** [comment] 2024-07-06 21:31
> in the trident tutorial area, none of the books have enchantments on them ![image](https://private-user-images.githubusercontent.com/91225097/335829869-d5a06ed0-60be-48c7-afb8-8940643dc9ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMDE1NDUsIm5iZiI6MTcyMDMwMTI0NSwicGF0aCI6Ii85MTIyNTA5Ny8zMzU4Mjk4NjktZDVhMDZlZDAtNjBiZS00OGM3LWFmYjgtODk0MDY0M2RjOWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDIxMjcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MWQ0OTdhMWI5YmNkNzE3M2ZlNGE1NjU2NTRkNDhhNDY2YTExMTZkZDExNDYyNzM3NTcwNmE2ZTBmYjVhNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0LLCeH4PDBifg0iR7bRn4GpHIUyqqOxoXNXSGL6-BWo) (i already used the exp bottles in the picture) all of the books are like this.
> 
> running 1.20.6 on fabric

what enchantments should they have?

**Comment by Wilyicaro** [comment] 2024-07-10 06:30
Fixed in version 1.7, thanks for reporting.

**Closed by Wilyicaro** 2024-07-10 06:30 UTC
