### ISSUE TITLE
Paper doll renders with low frame rate

### ISSUE THREAD

**Issue by Fuzss** [Wilyicaro/Legacy-Minecraft#153] opened 2024-03-08 11:11 UTC
The mini player model is very choppy, this is because `InventoryScreen::renderEntityInInventory` sets the `partialTick` parameter to `1.0F`, instead of using the actual value for the current render tick.

Just duplicating the vanilla method and passing the current `partialTick` value is enough to make the player model render smoothly.

https://github.com/Wilyicaro/Legacy-Minecraft/blob/e491d807db7c0666926b8ad03a571a220c382ce4/common/src/main/java/wily/legacy/mixin/GuiMixin.java#L130

**Comment by DanielMC101** [comment] 2024-03-08 17:01
It's supposed to be like this, as this is also what it does in legacy console

**Comment by Wilyicaro** [comment] 2024-03-08 22:24
And unfortunately, if I pass the current partialTick to a duplicate of the `InventoryScreen::renderEntityInInventory` method, this will need a workaround, because it needs to be changed certain rotations of the LocalPlayer, which causes a "jitter" in the model when rendering with the current partialTick in the `EntityRenderDispatcher::render` method

**Closed by Wilyicaro** 2024-03-08 22:24 UTC
