### ISSUE TITLE
[Bug/Glitch] Hang (infinite loading) when trying to load world with any resource assort except default (1.14+ textures)

### ISSUE THREAD

**Issue by sussum2432** [Wilyicaro/Legacy-Minecraft#599] opened 2024-09-15 08:52 UTC
### Legacy4J Version

1.21-1.7.3

### Mod Loader Version

fabric 0.16.5

### Bug/Glitch Occurrence Context

try to load any world, select ANY resource assorted OTHER than default (the 1.14 and newer) textures
it will say preparing resource for 1 second, then music stop and infinite loading appears with the 8 square circle loading on black wallpaper

### Crash Report

https://mclo.gs/Q38GSTS

### What happened wrong?

it is infinite loading , no music etc, can ONLY close by task manager

**Comment by Wilyicaro** [comment] 2024-09-21 15:40
Fixed in version 1.7.4, thanks for reporting.

**Comment by Wilyicaro** [comment] 2024-09-22 06:50
apparently this wasn't fixed, and is a conflict with some mod

**Comment by universitar1o144** [comment] 2024-09-24 02:54
> I only have this issue when sodium is installed.

me too, i think its the cause.

**Comment by Wilyicaro** [comment] 2024-09-25 03:48
As I said in #609, the cause is certainly the Legacy Waters resource pack, as it's incompatible with Sodium, and since 1.7.4 it's enabled by default
So, you have to remove it manually from the resource assort, as when it's automatically removed during the world load, this infinite loading happens

**Comment by Wilyicaro** [comment] 2024-11-01 22:01
Fixed in 1.7.5.2444.0, thanks for reporting.

**Closed by Wilyicaro** 2024-11-01 22:01 UTC
Labels: bug
