### ISSUE TITLE
Crafting Interface option switches to classic crafting about 30 seconds after joining a world and then dying. Is force enabled until the world is reloaded.

### ISSUE THREAD

**Issue by JuniperIsSleepy** [Wilyicaro/Legacy-Minecraft#321] opened 2024-05-12 19:50 UTC
I talked about this here https://github.com/Legacy-Union/Re-Console/issues/20 and would like to bring it up to here as well, as the issue appears to originate from this mod. It does not seem to have an obvious cause.

Steps to reproduce:
1. Join or create a world. Check the crafting interface to see that is normal and classic crafting is off.
2. Play a bit.
3. Die in game.
4. Wait about 30 seconds, then try and open the crafting interface.

**Comment by Dekamir** [comment] 2024-05-14 17:02
Can reproduce. Both players lost the new crafting interface after dying.

**System** _(irrelevant but still)_**:**
Ryzen 7 5800X3D / Ryzen 7 5700X
NVIDIA GeForce RTX 3080 / 4070 Ti
32 GB DDR4 RAM (4 GB allocated to Java)
Windows 10 64 bit
Eclipse Adoptium Temurin 21

**Comment by BzzzThe18th** [comment] 2024-05-19 15:26
I experienced this issue as well. Additionally, the classic crafting toggle may stay toggled off, in which case only a rejoin is necessary.

**Comment by BlueSupernova22** [comment] 2024-05-20 00:38
same thing happened to me after dying, but for me apparently the classic crafting stayed on pretty much the whole time because no matter what world i played on the legacy crafting would still be disabled. I only managed to fix it by opening the options.txt in the game folder and changing the classic crafting to "false". I dont know if there is a hotkey for this but if not until this issue is fixed, this might be the only solution for now.

**Comment by Fireyvortex2112** [comment] 2024-05-24 09:47
I figured I'd say this is also happening to me, it seems to happen when loading chunks back up when spawning in a bed or whatever, I pressed x quick and the Legacy crafting was there but then it stuttered a bit and changed back to classic crafting, I'm running 1.20.4 Forge and other than that problem this mod is amazing it adds so much and its super stable, I've never played this much of the java edition I started on 360 and I'm just not a huge keyboard person once I get used to the game, if this was fixed it would be pretty much perfect. I'll help with any way I can!

**Comment by Wilyicaro** [comment] 2024-05-25 05:57
Fixed in version 1.6.4, thanks for reporting.

**Closed by Wilyicaro** 2024-05-25 05:57 UTC
