### ISSUE TITLE
[SUGGESTION] Add compatibility with ReplayMod

### ISSUE THREAD

**Issue by nenamoree9** [Wilyicaro/Legacy-Minecraft#548] opened 2024-08-06 19:24 UTC
So basically i installed the replay mod but the replay mod's settings is bugged and there's no option to pause or stop a recording in the pause menu.

**Comment by TheAwesome98-Real** [comment] 2024-08-08 21:25
this is a duplicate of my issue #540

**Comment by Wilyicaro** [comment] 2024-08-08 22:38
Suggestions will not be supported here, please make them on the [Legacy4J Discord server](https://modrinth.com/mod/legacy4j)

**Closed by Wilyicaro** 2024-08-08 22:38 UTC
