### ISSUE TITLE
Incompatibility with Polymer mixins

### ISSUE THREAD

**Issue by NotCitraEmu** [Wilyicaro/Legacy-Minecraft#90] opened 2024-02-08 03:57 UTC
Opening up the inventory when on the Hypixel server causes the entire game to crash

[crash-2024-02-07_21.01.45-client.txt](https://github.com/Wilyicaro/Legacy-Minecraft/files/14204026/crash-2024-02-07_21.01.45-client.txt)

**Comment by S-N00B-1** [comment] 2024-02-08 17:03
Caused by an incompatibility between polymer and legacy4j

**Comment by Wilyicaro** [comment] 2024-02-08 23:46
> Caused by an incompatibility between polymer and legacy4j

Exactly, not related to Hypixel server

**Comment by Wilyicaro** [comment] 2024-05-25 06:03
Fixed in version 1.6.4, thanks for reporting.

**Closed by Wilyicaro** 2024-05-25 06:03 UTC
